<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <!--
            Note: Source Generators are .NET Standard 2.0 components.
            Do NOT update TargetFramework to netstandard2.1 or anything else.
            See https://devblogs.microsoft.com/dotnet/introducing-c-source-generators/
         -->
        <TargetFramework>netstandard2.0</TargetFramework>
        <IsPackable>false</IsPackable>
        <Nullable>enable</Nullable>
        <LangVersion>latest</LangVersion>

        <EnforceExtendedAnalyzerRules>true</EnforceExtendedAnalyzerRules>
        <IsRoslynComponent>true</IsRoslynComponent>

        <RootNamespace>Dawn.SourceGen</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.CodeAnalysis.Analyzers" Version="3.3.4">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
        <PackageReference Include="Microsoft.CodeAnalysis.CSharp" Version="4.9.2"/>

        <PackageReference Include="Newtonsoft.Json" Version="13.0.3" PrivateAssets="all" GeneratePathProperty="true" />

        <!--
        Being a code analyzer & source generator package,
        its binary artifacts are placed at a special path
        analyzers/dotnet/cs instead of the usual lib/<tfm>/.

        The empty file named `_._` is packaged per official
        recommendation just to avoid NuGet Warning NU5128.

        https://learn.microsoft.com/en-us/nuget/reference/errors-and-warnings/nu5128
         -->
        <Content Include="lib/" Pack="True" PackagePath="lib/" BuildAction="None" />

        <None Include="$(PkgNewtonsoft_Json)\lib\netstandard2.0\*.dll"
            Pack="true" PackagePath="analyzers/dotnet/cs" Visible="false" />

        <None Include="bin\$(Configuration)\netstandard2.0\DawnLib.SourceGen.dll"
            Pack="true" PackagePath="analyzers/dotnet/cs" Visible="false" />
    </ItemGroup>
    <PropertyGroup>
        <GetTargetPathDependsOn>$(GetTargetPathDependsOn);GetDependencyTargetPaths</GetTargetPathDependsOn>
    </PropertyGroup>

    <!-- NuGet Packaging -->
    <PropertyGroup>
        <PackageId>TeamXiaolan.DawnLib.SourceGen</PackageId>
        <Description>Source generators to simplify DawnLib.</Description>
        
        <IsPackable>true</IsPackable>
        <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
        <IncludeBuildOutput>false</IncludeBuildOutput>
    </PropertyGroup>

    <Target Name="GetDependencyTargetPaths">
        <ItemGroup>
            <TargetPathWithTargetPlatformMoniker Include="$(PKGNewtonsoft_Json)\lib\netstandard2.0\Newtonsoft.Json.dll" IncludeRuntimeDependency="false" />
        </ItemGroup>
    </Target>

    <!--
        Release tracking analyzer
        https://github.com/dotnet/roslyn-analyzers/blob/main/src/Microsoft.CodeAnalysis.Analyzers/ReleaseTrackingAnalyzers.Help.md
     -->
    <ItemGroup>
        <AdditionalFiles Include="AnalyzerReleases.Shipped.md" />
        <AdditionalFiles Include="AnalyzerReleases.Unshipped.md" />
    </ItemGroup>

    <Target Name="PublishThunderstore">
    </Target>
</Project>
 